apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: estacionamento-itw-summit
  annotations:
    github.com/project-slug: deb-gama/estacionamento-itw
spec:
  type: other
  lifecycle: unknown
  owner: school-devops
